Vagrant.configure("2") do |config|
#server konfigurieren
	config.vm.define "db" do |db|
		db.vm.box = "ubuntu/xenial64"
		db.vm.network "private_network", ip: "192.168.50.110"
		db.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
		end
		db.vm.hostname = "db01"
		#MySQL nur im private network sichtbar
		#db.vm.network "forwarded_port", guest:3306, host:3306, auto_correct: true
	end
	#Wenn ich ein extra-File für das Provision hätte:
	config.vm.provision "shell", path: "db.sh"
end