Vagrant.configure("2") do |config|
	#Server konfigurieren (für Web)
	config.vm.define "web" do |web|
		web.vm.box = "ubuntu/xenial64"
		web.vm.network "private_network", ip: "192.168.50.100"
		web.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
		web.vm.hostname = "web01"
		web.vm.synced_folder ".", "/var/www/html/"
		web.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
	end
	
	web.vm.provision "shell", inline: <<-SHELL
		#Packete für Webserver installieren	
		 sudo apt-get update
		 sudo apt-get install -y apache2
		 sudo apt-get install -y webalizer
		
		#Firewall konfigurieren 
		 sudo apt-get -y install ufw
		 sudo ufw allow 80/tcp
		 sudo ufw allow from 10.0.2.2 to any port 22
		 sudo ufw allow from 192.168.43.203
		 sudo ufw -f enable
		 
		#Proxy Installation
		 #sudo apt-get install -y libapache2-mod-proxy-html libxml2-dev#<-- schon bei apache2 enthalten
		 sudo a2enmod proxy
		 sudo a2enmod proxy_html
		 sudo a2enmod proxy_http
		 sudo service apache2 restart
		SHELL
	end
#Server konfigurieren (für Datenbank)
	config.vm.define "db" do |db|
		db.vm.box = "ubuntu/xenial64"
		db.vm.network "private_network", ip: "192.168.50.100"
		db.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
		db.vm.hostname = "db01"
		db.vm.synced_folder ".", "/var/www/html/"
		db.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
	end

	db.vm.provision "shell", inline: <<-SHELL	
		set -o xtrace
			 sudo apt-get update
			 sudo apt-get -y install debconf-utils 
			 sudo apt-get -y install apache2 
			 sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password _PassW0rt!'
			 sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password _PassW0rt!'
			 sudo apt-get -y install php libapache2-mod-php php-curl php-cli php-mysql php-gd mysql-client mysql-server 
			# Admininer SQL UI 
			 sudo mkdir /usr/share/adminer
			 sudo wget "http://www.adminer.org/latest.php" -O /usr/share/adminer/latest.php
			 sudo ln -s /usr/share/adminer/latest.php /usr/share/adminer/adminer.php
			 echo "Alias /adminer.php /usr/share/adminer/adminer.php" | sudo tee /etc/apache2/conf-available/adminer.conf
			 sudo a2enconf adminer.conf 
			 sudo service apache2 restart 
			# Mysql User erstellen
			 sudo mysql -uroot -p_PassW0rt! %EOF%
			 create database if not exists M300_db;
			 create user "sarruja" identified by "Sarruja";
			 grant usage on M300_db.* to "sarruja" identified by "Sarruja";
			 grant all privileges on M300_db.* to "sarruja";
			 flush privileges;
			 %EOF%
			#Firewall konfigurieren 
			 sudo apt-get -y install ufw
			 sudo ufw allow 3306/tcp
			 sudo ufw allow from 192.168.43.203
			 sudo ufw -f enable
		SHELL
	end
end