Vagrant.configure("2") do |config|
	#Server konfigurieren (für Web)
	config.vm.define "web" do |web|
		web.vm.box = "ubuntu/xenial64"
		web.vm.network "private_network", ip: "192.168.50.100"
		web.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
		web.vm.hostname = "web01"
		web.vm.synced_folder ".", "/var/www/html/"
		web.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
	end
	
	web.vm.provision "shell", inline: <<-SHELL
		#Packete für Webserver installieren	
		 sudo apt-get update
		 sudo apt-get install -y apache2
		 sudo apt-get install -y webalizer
		
		#Firewall konfigurieren 
		 sudo apt-get -y install ufw
		 sudo ufw allow 80/tcp
		 sudo ufw allow from 10.0.2.2 to any port 22
		 sudo ufw allow from 192.168.43.203
		 sudo ufw -f enable
		 
		#Proxy Installation
		 #sudo apt-get install -y libapache2-mod-proxy-html libxml2-dev#<-- schon bei apache2 enthalten
		 sudo a2enmod proxy
		 sudo a2enmod proxy_html
		 sudo a2enmod proxy_http
		 sudo service apache2 restart
		SHELL
	end
end